stages:
- name: Build and Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./web/react/Dockerfile
      buildContext: ./web/react
      tag: simuha999/portfolio:version-${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
timeout: 30
branch: {}
