stages:
- name: Build and Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./web/react/Dockerfile
      buildContext: ./web/react
      tag: simuha999/portfolio
      pushRemote: true
      registry: index.docker.io
- name: Deploy YAML
  steps:
  - applyYamlConfig:
      path: ./ops/rancher/design.yaml
timeout: 60
branch: {}
