version: "2"
services:
  nodejs:
    build: ./web/nodejs
    command: gulp
  nginx:
    build: ./web/nginx
    ports:
      - "80:80"
      - "443:443"
    # prod
    # command: bash -c "npm install && node ./dist/index.js"
    

  # to start: docker-compose up


    # command: node ./dist/index.js
    # docker stop $(docker ps -a -q)
    # docker rm $(docker ps -a -q)
    
    # remove all images: docker rmi $(docker images -a -q)
    # remove all containers: docker stop $(docker ps -a -q)
    