apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: default
spec:
  acme:
    http01: {}
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jwc_miller@hotmail.com
    privateKeySecretRef:
      name: letsencrypt
    dns01:
      providers:
      - name: cf-dns
        cloudflare:
          email: jwc_miller@hotmail.com
          apiKeySecretRef:
            name: cloudflare-dns
            key: api-key
