apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: jamesmiller-blog
  namespace: wordpress
spec:
  secretName: jamesmiller-blog-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: www.jamesmiller.blog
  dnsNames:
    - jamesmiller.blog
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - www.jamesmiller.blog
      - jamesmiller.blog
