apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: design-app-deployment
spec:
  replicas: 1 # We want two pods for this deployment
  template:
    metadata:
      labels:
        app: design-app
    spec:
      containers:
      - name: design-app
        image: simuha999/portfolio
        ports:
        - containerPort: 3000
      restartPolicy: Always
---
  apiVersion: v1
  kind: Service
  metadata:
    name: design-app
    labels:
      run: design-app
  spec:
    type: NodePort
    ports:
    - port: 3000
      protocol: TCP
      name: http
    selector:
      app: design-app
